#CREATING BROTHERS AND SISTERS TUPLE
BROTHERS_TUPLE = ("RAM","RAHUL","SUMANTH")
SISTERS_TUPLE = ("SITA","MAHI","VINNI")
print("BROTHERS:")
for i in BROTHERS_TUPLE:
  print(i)
print("----------")
print("SISTERS:")
for i in SISTERS_TUPLE:
  print(i)
SIBLING_TUPLE=BROTHERS_TUPLE+SISTERS_TUPLE
print("-------------")
print("SIBLINGS:")
print(SIBLING_TUPLE)
print("NUMBER OF SIBLINGS= "+str(len(SIBLING_TUPLE)))
print("CHANGING THE TUPLE:")
#converting the tuple into list and list to tuple
SIBLING_LIST=list(SIBLING_TUPLE)
SIBLING_LIST[1]="RAJU"
SIBLING_TUPLE=tuple(SIBLING_LIST)
print(SIBLING_TUPLE)
print("---------------------")
print("CREATE A PARENT TUPLE AND INSERT MOTHER AND FATHER INTO TUPLE")
print("CONCATINATING PARENTS AND SIBLINGS")
FAMILY_MEMBERS=("DANIEL","TANVIKA")+SIBLING_TUPLE
print("FAMILY_MEMBERS:"+str(FAMILY_MEMBERS))